# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

entropyCpp <- function(x) {
    .Call('RStoolbox_entropyCpp', PACKAGE = 'RStoolbox', x)
}

gainOffsetRescale <- function(x, g, o) {
    .Call('RStoolbox_gainOffsetRescale', PACKAGE = 'RStoolbox', x, g, o)
}

normImageCpp <- function(x, M, S) {
    .Call('RStoolbox_normImageCpp', PACKAGE = 'RStoolbox', x, M, S)
}

predKmeansCpp <- function(x, centers) {
    .Call('RStoolbox_predKmeansCpp', PACKAGE = 'RStoolbox', x, centers)
}

specSimC <- function(x, em) {
    .Call('RStoolbox_specSimC', PACKAGE = 'RStoolbox', x, em)
}

spectralIndicesCpp <- function(x, indices, redBand, blueBand, greenBand, nirBand, swir2Band, swir1Band, L, s, G, C1, C2, Levi) {
    .Call('RStoolbox_spectralIndicesCpp', PACKAGE = 'RStoolbox', x, indices, redBand, blueBand, greenBand, nirBand, swir2Band, swir1Band, L, s, G, C1, C2, Levi)
}

