# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

whichColMinC <- function(x, centers) {
    .Call('RStoolbox_whichColMinC', PACKAGE = 'RStoolbox', x, centers)
}

